var first_name = "Rabir";
var last_name = "kapoor";
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 10;
var b = 3;
var add = a+b;
console.log(add);
var sub = a-b;
console.log(sub);